### ISSUE TITLE
Technical Glitch Found While Using multi_camera_multi_tracker demo.

### ISSUE THREAD

**Issue by shirish100** [openvinotoolkit/open_model_zoo#1675] opened 2020-10-20 13:17 UTC
I have used this example before I upgraded the system with the newest version of open_vino (2021.1).  The inference of the model seems to have vanished. I have attached the images for your reference. please assist since open_vino is our base for inference.
This problem seems to be repeating in spite of changing the models present in open_model_zoo for person_detection.
The image consists of code and log output

![Technical_Issue1](https://user-images.githubusercontent.com/16833805/96591225-aa20b800-1304-11eb-94f4-6fd71c09dba0.png)
![Technical_Issue](https://user-images.githubusercontent.com/16833805/96591240-af7e0280-1304-11eb-8e21-eb37cadaa121.png)

**Comment by shirish100** [comment] 2020-10-20 14:39
Previously I used to get these logs 
[[TrackedObj(rect=(1002, 414, 1161, 901), label='ID 0'), TrackedObj(rect=(1273, 92, 1551, 885), label='ID 1')],[TrackedObj(rect=(1002, 414, 1161, 901), label='ID 0'), TrackedObj(rect=(1273, 92, 1551, 885), label='ID 3'),TrackedObj(rect=(1273, 92, 1551, 885), label='ID 5')]]

**Comment by vladimir-dudnik** [comment] 2020-10-20 23:52
@shirish100 I did not get what is the issue on your side? Is that demo does not detect anything?

**Comment by shirish100** [comment] 2020-10-21 00:29
Looks like that. The detection of person using person detection model are not seen in the logs and no bounding box is drawn in the output video.

**Comment by shirish100** [comment] 2020-10-21 00:37
The logs in the second comment are the logs I used to get when using open vino 2020.4 version. But with new open vino 2021.1 version and new models that are updated in open model zoo I don't see bounding box being drawn on the output video. And when I started troubleshooting I found that the person's detection seems to have got vanished. Can you help me to solve as what could be the issue that person's are not getting detected.
I am using multi_camera_multi_tracker demo from python demos folder

**Comment by Shirish-Ranoji** [comment] 2020-10-21 09:19
@vladimir-dudnik To fasten up my process of troubleshooting what can I do to resolve the above issue?

**Comment by Shirish-Ranoji** [comment] 2020-10-21 12:12
@snosov1  @vladimir-dudnik  Can you please suggest me something? Should I go for the reinstallation of open_vino_2021.1?

**Comment by Wovchena** [comment] 2020-10-26 14:01
Hi
I can't reproduce the glitch. The demo draws bounding boxes for me. I did the following:
`py "C:\Program Files (x86)\IntelSWTools\openvino_2021.1.110\deployment_tools\open_model_zoo\tools\downloader\downloader.py" --name person-detection-retail-0013,person-reidentification-retail-0288 --precisions FP16 -o C:\Users\vzlobin\Downloads\multi_camera_multi_target_tracking`

`"C:\Program Files (x86)\IntelSWTools\openvino_2021.1.110\bin\setupvars.bat"`

`py "C:\Program Files (x86)\IntelSWTools\openvino_2021.1.110\deployment_tools\open_model_zoo\demos\python_demos\multi_camera_multi_target_tracking\multi_camera_multi_target_tracking.py" -i C:\Users\vzlobin\Videos\people-detection.mp4 -m C:\Users\vzlobin\Downloads\multi_camera_multi_target_tracking\intel\person-detection-retail-0013\FP16\person-detection-retail-0013.xml --m_reid C:\Users\vzlobin\Downloads\multi_camera_multi_target_tracking\intel\person-reidentification-retail-0288\FP16\person-reidentification-retail-0288.xml`

May be your version of `multi_camera_multi_target_tracking` was modified somewhere else. I can suggest to check if the unmodified version from openvino_2021.1.110 or `master` branch of this repo works for you.

**Comment by Shirish-Ranoji** [comment] 2020-10-27 06:38
Hi,

@Wovchena @vladimir-dudnik 

Thank you for the solution
The problem was with the detection model (person-detection-0202) I was using. 
You can check that there are no detections with the model person-detection-0202.  I have double-checked it with this model, but there are no detections.
Can you please tell me the difference between the models? One has retail and the other doesn't. has retail at the end.

**Comment by Wovchena** [comment] 2020-10-27 11:10
Replacing https://github.com/openvinotoolkit/open_model_zoo/blob/75ec8ad4b6c4fd7fb161ae9d2c3056281b2443de/demos/python_demos/multi_camera_multi_target_tracking/configs/person.py#L4 with `trg_classes=(0,)` should fix the problem.

It looks a label for a valid detection for `person-detection-0202` is `0`, while for `person-detection-retail-0013` it's `1`. @vladimir-dudnik, should something be done about that inconsistency from models perspective?

**Comment by vladimir-dudnik** [comment] 2020-11-08 12:41
@snosov1 could you please add to model descriptions some info on meaning of detected labels/classid?

**Comment by snosov1** [comment] 2020-11-09 05:50
@Ilya-Krylov Looks like we need to provide the mapping for labels somewhere

**Comment by vladimir-dudnik** [comment] 2021-02-15 21:14
@Shirish-Ranoji class id description added to model documentation. Do you have additional questions?

**Comment by vladimir-dudnik** [comment] 2021-09-10 21:47
closing as answered

**Closed by vladimir-dudnik** 2021-09-10 21:47 UTC
