### ISSUE TITLE
"malloc(): unsorted double linked list corrupted" problem on raspberry pi4 when I run the C++ demo smart_classroom_demo

### ISSUE THREAD

**Issue by engineer0204** [openvinotoolkit/open_model_zoo#1852] opened 2020-11-28 10:42 UTC
when I run the C++ demo smart_classroom_demo on Ubuntu it's working well,
but when I run the C++ demo smart_classroom_demo on raspberry pi4, 
I got the error message "malloc(): unsorted double linked list corrupted"
I want to know how to solve this problem.
thanks
```
pi@raspberrypi:~/open_model_zoo/demos/build/armv7l/Release $ ./smart_classroom_demo -m_fd ~/model/face-detection-adas-0001.xmlGi -m_act ~/model/person-detection-action-recognition-0005.xml -i ~/ncs2_test/May.mp4 -d_act MYRIAD -d_fd MYRIAD -d_lm MYRIAD -d_reid MYRIAD
[ INFO ] InferenceEngine: 	API version ......... 2.1
	Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1
[ INFO ] Parsing input parameters
[ INFO ] Loading Inference Engine
[ INFO ] Device info: 
	MYRIAD
	myriadPlugin version ......... 2.1
	Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1

malloc(): unsorted double linked list corrupted
已經終止
```
----------------------------------------------------------------------------------------
btw. on Ubuntu it's working well
```
dvlab@dvlab-Z370M-D3H:~/inference_engine_demos_build/intel64/Release$ ./smart_classroom_demo -m_act ~/models/person-detection-action-recognition-0005.xml -m_fd ~/models/face-detection-adas-0001.xml -i /home/dvlab/下載/sit.mp4 -d_act MYRIAD -d_fd MYRIAD -d_lm MYRIAD -d_reid MYRIAD
[ INFO ] InferenceEngine: 	API version ......... 2.1
	Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1
[ INFO ] Parsing input parameters
[ INFO ] Loading Inference Engine
[ INFO ] Device info: 
	MYRIAD
	myriadPlugin version ......... 2.1
	Build ........... 2021.1.0-1237-bece22ac675-releases/2021/1

[ WARNING ] Face recognition models are disabled!
To close the application, press 'CTRL+C' here or switch to the output window and press ESC key

[ INFO ] Mean FPS: 3.67467
[ INFO ] Frames processed: 15

[ INFO ] Execution successful
```

**Comment by vladimir-dudnik** [comment] 2020-11-29 16:24
@terfendail could you please check this on RasperryPi board and OpenVINO 2021.1?

**Comment by terfendail** [comment] 2020-12-01 17:15
I've reproduced the issue using OpenVINO 2021.1 for Raspbian and native compilation of smart_classroom_demo. Going to investigate it further

**Comment by engineer0204** [comment] 2020-12-01 22:25
thank you guys
Let me know if you need any further test or any infomation that i could offer

**Comment by terfendail** [comment] 2020-12-02 12:25
@ilya-lavrenov Could you please share your thoughts on this?

**Comment by engineer0204** [comment] 2020-12-02 13:38
In my opinion maybe it's because of the 32-bit raspbian OS.
It's too small to memory allocation or what. sorry I'm not good at it.

**Comment by vladimir-dudnik** [comment] 2020-12-03 09:19
@engineer0204 the issue might be related with the fact that OpenVINO RaspberryPi package built by cross-compilation tools, not native one (although versions of gcc are the same). And then, when you build application by native tools and link with OpenVINO libraries built by cross-compiler tools, there are some runtime issues. We are investigating this.

@asuhov FYI

**Comment by thiagortk** [comment] 2021-04-12 14:53
Hey guys,

Any news about that?

**Comment by dkurt** [comment] 2021-04-14 07:20
Hi! Please add compilation instructions. Have you added `-DCMAKE_CXX_FLAGS="-march=armv7-a"` flag?

**Comment by cosmos1982** [comment] 2021-04-22 09:00
@dkurt , Hi, I have the same error with @engineer0204 , I have tried -DCMAKE_CXX_FLAGS="-march=armv7-a", still same error....

**Comment by sepehr78** [comment] 2021-05-31 23:22
Any fixes?

**Comment by vladimir-dudnik** [comment] 2021-06-07 07:35
@sepehr78 unfortunately the root cause of issue still not identified yet.

@ilya-lavrenov @asuhov @dkurt @alvoron CC

**Comment by ilya-lavrenov** [comment] 2021-06-07 09:04
@vladimir-dudnik we still don't know where the problem is located - inside demo builds or inside OpenVINO binaries..

**Comment by terfendail** [comment] 2021-06-10 13:15
@cosmos1982 Could you please share whole build command you use? It could be useful to try to reproduce your case

**Comment by alvoron** [comment] 2021-07-15 14:30
@ilya-lavrenov the same issue was observed recently: https://github.com/openvinotoolkit/open_model_zoo/issues/2589
I verified that the flag `-DCMAKE_CXX_FLAGS="-march=armv7-a"` solves the issue, it helps the author as well. 
Vitaly Tuzov has reproduced this issue some time ago and this flag works for him as well.
Should we add this flag explicitly?

**Comment by dkurt** [comment] 2021-07-26 08:05
@alvoron, this is an issue related to Raspbian GCC compiler. By default, it specifies armv6 instruction set.

**Comment by alvoron** [comment] 2021-07-26 09:09
@dkurt I have found that gcc 8 specifies armv6, however gcc 10 uses armv7-a.
I had a talk with Ilya Lavrenov, we decided to set architecture to armv7-a in demo\sample build scripts if the platform is ARM x32 and it's not cross-compilation.
Are you OK with such solution?

**Comment by dkurt** [comment] 2021-07-26 12:09
@alvoron, it's better to check for CPU arch. I recommend to set `-march=armv7-a` if `uname -m` returns `armv7l`

**Comment by alvoron** [comment] 2021-08-23 08:06
@vladimir-dudnik I suppose, this issue could be closed since OMZ fix has been merged.

**Comment by vladimir-dudnik** [comment] 2021-08-31 16:25
@alvoron yes, I'll close it once OpenVINO 2021.4.1 will be published

**Comment by vladimir-dudnik** [comment] 2021-09-10 21:43
OpenVINO 2021.4.1 which provides fix for the issue just [published](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/NEW-Intel-Distribution-of-OpenVINO-toolkit-2021-4-1-Long-Term/m-p/1313364#M25192), so I'm going to close this. Feel free to reopen if you still experience throubles

**Closed by vladimir-dudnik** 2021-09-10 21:43 UTC
Labels: ARM, RaspberryPi
