### ISSUE TITLE
text to speech demo with 2022.1 : Issue with bigger sentences. 

### ISSUE THREAD

**Issue by smitesh-sutaria** [openvinotoolkit/open_model_zoo#3393] opened 2022-03-23 05:58 UTC
Hello, 

multi-0001 models:

Gave the below input as text : "Conversational AI is the synthetic brainpower that makes machines capable of understanding, processing and responding to human language."

The audio output came only for last few words repeatedly.

Though the shorter sentences worked fine.

Also, the melgan default width has been changed from 80 to 800 ??

**Comment by smitesh-sutaria** [comment] 2022-03-23 06:04
Specially if longer sentences don't have delimiters.

**Comment by vladimir-dudnik** [comment] 2022-03-23 08:23
@smitesh-sutaria confirm the issue, we will look at it. Meanwhile, you can run demo with options `-s_id 1` and `-a 0.8` to generate the whole phrase

@anzhella-pankratova @eaidova @akorobeinikov @ivikhrev @Wovchena @a-a-egorovich

**Comment by smitesh-sutaria** [comment] 2022-03-23 08:30
> @smitesh-sutaria confirm the issue, we will look at it. Meanwhile, you can run demo with options `-s_id 1` and `-a 0.8` to generate the whole phrase
> 
> @anzhella-pankratova @eaidova @akorobeinikov @ivikhrev @Wovchena @a-a-egorovich

-a 0.8  : is very fast and not recommended for close to human like voice

**Comment by smitesh-sutaria** [comment] 2022-03-23 08:36
3 changes, want to know your opinion:

1. change len_th = 80 in main() in text_to_speech_demo.py
2. add ',' as a delimiter.  delimiters = '.!?;:,' 
3. change default_width for MelGANIE to 80. (from 800)

With above changes, we get better inference for longer sentences + ',' as delimeter

**Comment by vladimir-dudnik** [comment] 2022-03-23 08:57
@smitesh-sutaria I do not have an immediate answer, but I've created ticket for the issue, development team will look at this and get back with answers

**Comment by smitesh-sutaria** [comment] 2022-03-23 10:02
@vladimir-dudnik @anzhella-pankratova @eaidova @akorobeinikov @ivikhrev @Wovchena @a-a-egorovich

Have created a pull request : https://github.com/openvinotoolkit/open_model_zoo/pull/3395

**Comment by a-a-egorovich** [comment] 2022-03-23 12:35
the root cause of this problem is line 235 in https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/text_to_speech_demo/python/models/forward_tacotron_ie.py.
The mels.append(mel) must be changed to mels.append(np.copy(mel)).

**Comment by smitesh-sutaria** [comment] 2022-03-23 12:47
![image](https://user-images.githubusercontent.com/66471437/159702410-e8e03867-b10d-4788-925b-e6c6db34c7c7.png)

The previous 2021.4 version had no changes related to it. But it used to work for such sentences. How this change is impacting now ?

**Comment by eaidova** [comment] 2022-03-24 12:41
@smitesh-sutaria thank you for your contribution! We merged your PR with fix to master branch. Can we close this issue?

**Comment by smitesh-sutaria** [comment] 2022-03-24 12:50
@eaidova : Thank you. Yes, it can be closed now.

**Closed** 2022-03-24 12:51 UTC
Labels: bug, demo
